#!/usr/bin/with-contenv bash

# This is the init file used for adding os or pip packages to install lists.
# It takes advantage of the built-in init-mods-package-install init script that comes with the baseimages.
# If using this, we need to make sure we set this init as a dependency of init-mods-package-install so this one runs first

if [ ! -e "kcc/KCC_VERSION" ]; then
    echo "**** Adding kcc and its deps to package install lists ****"
    echo "\
            PySide6 \
            Pillow \
            psutil \
            requests \
            python-slugify \
            raven \
            mozjpeg-lossless-optimization \
            natsort[fast] \
            distro" >> /mod-pip-packages-to-install.list
    ## Ubuntu
    if [ -f /usr/bin/apt ]; then
        echo "\
            python3 \
            python3-pip 
            python3-dev \
            libpng-dev \
            libjpeg-dev \
            p7zip-full \
            p7zip-rar unrar-free \
            libgl1 \
            python3-pyqt5 \
            cmake" >> /mod-repo-packages-to-install.list
    fi
    # Alpine
    if [ -f /sbin/apk ]; then
        echo "\
            cargo \
            libffi-dev \
            openssl-dev \
            python3 \
            python3-dev \
            python3 \
            py3-pip" >> /mod-repo-packages-to-install.list
    fi
else
    echo "**** kcc already installed, skipping ****"
fi
